name: Team approval workflows
on:
  pull_request_review:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: 'region.'
        options:
          - 'us-east-1'
          - 'us-west-2'
jobs: 
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
    # - name: Label approved pull requests
    #   uses: abinoda/label-when-approved-action@1.0.5
    # env:
    #   REGION: ${{ github.event.inputs.region}}
    #   # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   # ADD_LABEL: "approved"
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Run Script
      env:
        REGION: ${{ github.event.inputs.region}}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ADD_LABEL: "approved"
      run: npm run script
      # run: REGION=${{ github.event.inputs.region}} npm run script
    

    
